name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  quest_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12' # Replace with the version you need

    - name: Install dependencies # Add explicit dependencies as necessary
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install pipreqs
        pip install sqlalchemy
        pip install pytest-asyncio

    - name: Generate Requirements
      run: |
        pipreqs quest_test --savepath test-requirements.txt
        pipreqs src --savepath src-requirements.txt
        cat test-requirements.txt src-requirements.txt | sort | uniq > requirements.txt

    - name: Install Requirements
      run: |
        echo quest==0.1.1 > requirements.ignore
        pip install -r requirements.txt

    - name: Run tests
      env:
        PYTHONPATH: ${{ github.workspace }}/src
      run: |
        pytest quest_test -o log_cli=true
